# Generated by Django 3.2.5 on 2021-08-14 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0002_auto_20210811_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(max_length=500),
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=500)),
                ('course', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=50)),
                ('Date_of_admission', models.DateField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homeApp.student')),
            ],
        ),
    ]
